### ISSUE TITLE
Create Configurer analogous to StormpathWebSecurityConfigurer in non-web module

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#511]
A user trying to use Spring Security is forced to depend on `stormpath-spring-security-webmvc`. They should have something analogous to this configurer in `stormpath-spring-security`

**Comment by lhazlewood** [comment]
This is because spring security generally depends on web concepts for much of its work, so we avoided the `stormpath-spring-security` (without web support) because it would be rather difficult.

Just curious - is there a customer request to isolate this?

**Comment by rocketraman** [comment]
> Just curious - is there a customer request to isolate this?

Hi Les. Yes, I wanted to use Stormpath + Spring Security to build an SPA/mobile REST backend. The webmvc starter comes with capability I don't want i.e. the view end of things.

Using stormpath-spring-security doesn't try to take over the view end of things, but also does not provide the useful backend stuff like `http.apply(stormpath())`.

So far I'm having some luck with leveraging webmvc but disabling all the endpoints (except logout) exposed by stormpath-webmvc, though I haven't gone too far down this path yet, so I may run into issues later:

```yaml
stormpath:
  web:
    login:
      enabled: false
    logout:
      enabled: true
    change:
      enabled: false
    forgot:
      enabled: false
    register:
      enabled: false
    sendVerificationEmail:
      enable: false
    verify:
      enabled: false
```

The only thing is I have to implement my own endpoints for each of the above functions.
